// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr7kP2DWAiWhP3BzGu1G8AfUP8wqxl9wk',
    appId: '1:779535312649:web:2377758b159ceaea1295d8',
    messagingSenderId: '779535312649',
    projectId: 'flutter-project-1b754',
    authDomain: 'flutter-project-1b754.firebaseapp.com',
    storageBucket: 'flutter-project-1b754.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN2Ovt488X4-9U91XlEJTrmjP7jBPjoRI',
    appId: '1:779535312649:android:e68fc1b0935910451295d8',
    messagingSenderId: '779535312649',
    projectId: 'flutter-project-1b754',
    storageBucket: 'flutter-project-1b754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBei2tKQzJWkT2Cbz-O5-yde8BWNVCCj8',
    appId: '1:779535312649:ios:cc21544789a5ce061295d8',
    messagingSenderId: '779535312649',
    projectId: 'flutter-project-1b754',
    storageBucket: 'flutter-project-1b754.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBei2tKQzJWkT2Cbz-O5-yde8BWNVCCj8',
    appId: '1:779535312649:ios:cc21544789a5ce061295d8',
    messagingSenderId: '779535312649',
    projectId: 'flutter-project-1b754',
    storageBucket: 'flutter-project-1b754.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr7kP2DWAiWhP3BzGu1G8AfUP8wqxl9wk',
    appId: '1:779535312649:web:c9fdc1a426e81dfa1295d8',
    messagingSenderId: '779535312649',
    projectId: 'flutter-project-1b754',
    authDomain: 'flutter-project-1b754.firebaseapp.com',
    storageBucket: 'flutter-project-1b754.firebasestorage.app',
  );
}
